apiVersion: v1
kind: Namespace
metadata:
  name: hellokitty-prod
  labels:
    environment-id: env_ea34fbe1-b2ad-45cc-8b97-ad41c61e5ffb
    project-id: project_5ac06bde-7b91-44e6-9166-9a1ae1d18ed7
    project-name: HelloKitty
    environment-name: prod
    organization-id: org_99bfadb5-996a-47d5-a5fc-442c14a28627
